# Generated by Django 6.1.1 on 2026-10-05 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("company", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="2-letter country code", max_length=2
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("BDT", "Bangladeshi Taka"),
                        ],
                        default="BDT",
                        max_length=3,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("fixed", "Fixed")],
                        default="hourly",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("BDT", "Bangladeshi Taka"),
                        ],
                        default="BDT",
                        max_length=3,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_client_name_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "client"], name="clients_pro_owner_i_7319bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_project_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("billing_type", "hourly"),
                        ("fixed_price__isnull", True),
                        ("hourly_rate__isnull", False),
                    ),
                    models.Q(
                        ("billing_type", "fixed"),
                        ("fixed_price__isnull", False),
                        ("hourly_rate__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check_billing_type_rates",
                violation_error_message="Hourly projects must have an hourly rate and no fixed price. Fixed projects must have a fixed price and no hourly rate.",
            ),
        ),
    ]
